sudo: false

install: libicu-dev cmake

cache: bundler

language: ruby

rvm:
  - "2.1.3"

notifications:
  slack: manacore:vn9ITXRs0av3S9kwXresy57Z

branches:
  except:
    - html

addons:
  code_climate:
    repo_token: a5960eb8e84098e99c5b35ce31ab5ee6fee35f99e2e5e5322d5cf1f168b9edb8
